.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,19 +13,11 @@ jobs:
     - name: checkout code
       uses: actions/checkout@v3
 
-    - name: rebase code
-      run: |
-        git config user.name "Github Actions"
-        git config user.email "actions@github.com"
-        git config core.editor true
-        TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
-        git fetch origin main
-        git rebase -i origin/main
-        git commit --allow-empty -m "rebase, $TIMESTAMP"
-        git push origin main --force
     
     - name: build image
-      run : docker build -t manjunadh965/expense:${{ github.sha }} .
+      run : |
+      docker build -t manjunadh965/expense:${{ github.sha }} .
+      
 
     - name: docker login 
       uses: docker/login-action@v2
@@ -35,3 +27,23 @@ jobs:
     
     - name: push image
       run : docker push manjunadh965/expense:${{ github.sha }}
+
+    - name: deployment in ec2
+      run: |
+      curl -o $(pwd)/testing.pem ${{ secrets.TEST_URL }}
+      ssh -o StrictHostKeyChecking=no -i testing.pem ubuntu@${{ secrets.EC2_HOST}} << 'EOF'
+        sudo docker pull manjunadh965/expense:${{ github.sha }}
+        sudo docker stop service || true
+        sudo docker rm service || true
+        sudo docker run -d --env-file .env --name service -p 8600:8600 manjunadh965/expense
+      EOF
+    
+    - name: cleaning files
+      run: rm -f testing.pem
+    
+    # - name: post msg in ms teams
+    #   uses: opsless/ms-teams-github-actions@main
+    #   if: always() # to let this step always run even if previous step failed
+    #   with:
+    #     github-token: ${{ github.token }}
+    #     webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
